### PR TITLE
[master] Fixes for addon.xml descriptions

### PR DESCRIPTION
**Pull request by gade01**
This fixes errors in addon.xml descriptions.

Descriptions in those 4 addons contain `"` characters, where they should be `&quot;`.

### CODE REVIEW

**Comment by garbear** [comment]
Shouldn't these be `&quot;`?

**Comment by gade01** [comment]
Hmm... this is how it's done in po files:
https://github.com/xbmc/xbmc/blob/master/addons/resource.language.en_gb/resources/strings.po#L4299

**Comment by gade01** [comment]
@garbear 
I did a lot of testing and you're right.
`&quot;` should be used in addon.xml

**Review by garbear — APPROVED** [review]

**Comment by gade01** [comment]
Squash and merge or just merge?

**Comment by garbear** [comment]
In code repos I prefer squashing with git and doing a normal merge, but for data repos like this I don't care, so you can just hit that green button (or squash with `git rebase -i HEAD~2` to work on that git-fu)

**Pull request merged**
