### PR TITLE
Add more controllers

### PR DESCRIPTION
**Pull request by zach-morris**
First attempt at creating a new controller addon

### CODE REVIEW

**Comment by garbear** [comment]
just saw this. awesome! I'll take a closer look when I get a chance this week

**Comment by zach-morris** [comment]
When you do look at it, I'm not certain the layout for the wiimote is correct here anymore after looking at it more.  LR has multiple flavors of this type of controller, see [here](https://github.com/libretro/dolphin/blob/master/Source/Core/DolphinLibretro/Input.cpp#L397).  The 'pointer' might be considered an analog, or a mouse, or both?  depending on how the controller is being emulated.  Should the wiimote be broken down into 5 flavors?
```
        {"WiiMote", RETRO_DEVICE_WIIMOTE},
        {"WiiMote (sideways)", RETRO_DEVICE_WIIMOTE_SW},
        {"WiiMote + Nunchuk", RETRO_DEVICE_WIIMOTE_NC},
        {"WiiMote + Classic Controller", RETRO_DEVICE_WIIMOTE_CC},
        {"Real WiiMote", RETRO_DEVICE_REAL_WIIMOTE}
```

**Comment by garbear** [comment]
The pointer should be an absolute pointer. It's describing what is emulated, not the internals of the emulator.

The all-caps IDs you posted are libretro "device subclasses". These are part of the libretro API, and so are internal to all emulators. You can read the specification here: https://github.com/libretro/RetroArch/blob/master/libretro-common/include/libretro.h#L867-L904.

Basically, a core can use the [`RETRO_DEVICE_SUBCLASS`](https://github.com/libretro/RetroArch/blob/master/libretro-common/include/libretro.h#L102) macro to derive classes of controllers from the older, more basic input abstraction (5 or 6 hardcoded models, e.g. `RETRO_DEVICE_JOYPAD`). Subclasses are defined by an integer OR-shifted with the base model.

While it was nice that the libretro input abstraction was improved, the intrinsic inheritance exploded the complexity when represented as XML. Instead, in https://github.com/kodi-game/controller-topology-project/pull/16 I switched to a flat data model: the list of controllers shown in the player GUI. If it makes sense to show all 5 variations in the GUI to let the player choose between what is being emulated or configured, then we should create 5 profiles and icons.

The game.libretro wrapper performs translation between our separate controller profiles and the hierarchical model used by libretro via the "subclass" attribute, as you can see in a sample [buttonmap.xml](https://github.com/kodi-game/game.libretro.bsnes-mercury-balanced/blob/master/game.libretro.bsnes-mercury-balanced/resources/buttonmap.xml).

For example, the line:

```xml
<controller id="game.controller.snes.mouse" type="RETRO_DEVICE_MOUSE" subclass="0">
```

Specifies that game.controller.snes.mouse should be converted to the integer 0 OR-shifted with `RETRO_DEVICE_MOUSE`.

Notice how dolphin doesn't propertly use `RETRO_DEVICE_SUBCLASS`, and instead duplicates the bitwise operations:

```c
#define RETRO_DEVICE_WIIMOTE ((1 << 8) | RETRO_DEVICE_JOYPAD)
#define RETRO_DEVICE_WIIMOTE_SW ((2 << 8) | RETRO_DEVICE_JOYPAD)
#define RETRO_DEVICE_WIIMOTE_NC ((3 << 8) | RETRO_DEVICE_JOYPAD)
#define RETRO_DEVICE_WIIMOTE_CC ((4 << 8) | RETRO_DEVICE_JOYPAD)
#define RETRO_DEVICE_REAL_WIIMOTE ((6 << 8) | RETRO_DEVICE_NONE)
```

This should actually look something like:

```c
#define RETRO_DEVICE_WIIMOTE  RETRO_DEVICE_SUBCLASS(RETRO_DEVICE_JOYPAD, 1)
#define RETRO_DEVICE_WIIMOTE_SW  RETRO_DEVICE_SUBCLASS(RETRO_DEVICE_JOYPAD, 2)
#define RETRO_DEVICE_WIIMOTE_NC  RETRO_DEVICE_SUBCLASS(RETRO_DEVICE_JOYPAD, 3)
#define RETRO_DEVICE_WIIMOTE_CC  RETRO_DEVICE_SUBCLASS(RETRO_DEVICE_JOYPAD, 4)
#define RETRO_DEVICE_REAL_WIIMOTE  RETRO_DEVICE_SUBCLASS(RETRO_DEVICE_NONE, 6)
```

Then, these subclasses could be declared in dolphin's buttonmap.xml to inform the emulator how to map our controller profiles to libretro device subclasses.

**Comment by garbear** [comment]
@zach-morris https://github.com/zach-morris/controller-topology-project/pull/1

can you squash the png crush commit? diffing large binaries bloats the repo size

**Comment by zach-morris** [comment]
Sorry, this one fell off my radar.  Looks like you already merged it though?  If there's any other controllers to try and tackle let me know.

**Comment by garbear** [comment]
Looks like something went wrong (I checked https://github.com/kodi-game/controller-topology-project/network). Want to rebase on master?

**Comment by garbear** [comment]
> If there's any other controllers to try and tackle let me know.

I re-published OpenEmu controller art under the same BSD license: https://github.com/kodi-game/OpenEmuControllerArt

It should be quick to check if there's any new controller art in their repo, in which case we can import it and later make add-ons out of it.

**Comment by zach-morris** [comment]
> Looks like something went wrong (I checked https://github.com/kodi-game/controller-topology-project/network). Want to rebase on master?

I think it's clear I have no idea what I'm doing when it comes to squashing/rebasing.  I *think* i did it correctly.  I did check openemu and dont see any new controllers present

**Comment by garbear** [comment]
Don't bother opening a new PR, when you force-push this one will be updated.

I can walk you through some steps. First do a hard-reset and make all the bad stuff go away:

```
git reset --hard 9f98d26ee88b090ebf4527d712d3243e1e4afb02
```

Then, we want to squash out the png change commit, so do an interactive rebase on this repo's master branch:

```
git rebase -i 0c75cab85e534fe9ad029678fe2a6144f5c24ae1
```

Change the third commit to an `f`, so it looks like this:

```
pick 5214bd2 Add Wiimote addon
pick 4e96f44 Adding pokemini controller
f 16fbdad crush pngs
```

Save and exit, then force-push:

```
git push -f origin master
```

**Comment by zach-morris** [comment]
Thanks.  Git is as hard as i am slow!

**Comment by garbear** [comment]
CI flagged some issues: https://github.com/xbmc/repo-resources/pull/84. I'll take care of them unless you get to them first

**Comment by garbear** [comment]
@zach-morris https://github.com/kodi-game/controller-topology-project/pull/36

**Pull request merged**
